using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using System.CodeDom.Compiler;
using System.CodeDom;

namespace NodeService.Endpoints
{
    public abstract class StrongTypedNodeEndpointClient : INodeEndpointClient
    {
        private static Dictionary<Type, Type> clientImplementations = new Dictionary<Type, Type>();

        public INodeEndpointClientProvider Provider { get; private set; }
        public StrongTypedNodeEndpointSerializer Serializer { get; private set; }

        public StrongTypedNodeEndpointClient(INodeEndpointClientProvider provider)
        {
            this.Provider = provider;
        }

        public void Dispose()
        {
            if (this.Provider.Protocol != null)
            {
                this.Provider.Protocol.Disconnect();
            }
        }

        protected void Initialize(Type interfceType)
        {
            this.Serializer = new StrongTypedNodeEndpointSerializer();
            foreach (var methodInfo in this.GetType().GetMethods())
            {
                foreach (var type in methodInfo
                    .GetParameters()
                    .Select(p => p.ParameterType)
                    .Concat(new Type[] { methodInfo.ReturnType })
                    .Where(t => t != typeof(INodeEndpointRequest) && t != typeof(void))
                    )
                {
                    this.Serializer.AddDefaultSerializer(type);
                }
            }
        }

        protected object Execute(string method, Type type, string[] names, object[] arguments)
        {
            XElement body = new XElement("Parameters",
                names
                .Zip(arguments, (a, b) => Tuple.Create(a, b))
                .Select(t => new XElement(t.Item1, this.Serializer.Serialize(t.Item2)))
                );
            var response = this.Provider.Send(method, body);
            response.WaitForResponse();
            if (response.RequestState == RequestState.RaisedException)
            {
                throw response.Exception;
            }
            else if (type != typeof(void))
            {
                return this.Serializer.Deserialize(response.Response, type);
            }
            else
            {
                return null;
            }
        }

        private static Type CreateClientImplementation(Type infertaceType)
        {
            Type clientType = null;
            if (!clientImplementations.TryGetValue(infertaceType, out clientType))
            {

                CodeDomProvider codedomProvider = CodeDomProvider.CreateProvider("CSharp");
                string namespaceName = "NodeService.StringTypedNodeEndpointClientAutoGeneratedClients";
                string typeName = "ImplementationOf" + infertaceType.Name;

                CodeCompileUnit codeCompileUnit = new CodeCompileUnit();
                {
                    CodeNamespace codeNamespace = new CodeNamespace(namespaceName);
                    codeCompileUnit.Namespaces.Add(codeNamespace);

                    CodeTypeDeclaration clientDeclaration = new CodeTypeDeclaration(typeName);
                    clientDeclaration.BaseTypes.Add(typeof(StrongTypedNodeEndpointClient));
                    clientDeclaration.BaseTypes.Add(infertaceType);
                    codeNamespace.Types.Add(clientDeclaration);

                    CodeConstructor clientConstructor = new CodeConstructor();
                    clientDeclaration.Members.Add(clientConstructor);
                    clientConstructor.Attributes = MemberAttributes.Public;
                    clientConstructor.Parameters.Add(new CodeParameterDeclarationExpression(typeof(INodeEndpointClientProvider), "provider"));
                    clientConstructor.BaseConstructorArgs.Add(new CodeArgumentReferenceExpression("provider"));
                    clientConstructor.Statements.Add(
                        new CodeExpressionStatement(
                            new CodeMethodInvokeExpression(
                                new CodeThisReferenceExpression(),
                                "Initialize",
                                new CodeTypeOfExpression(typeof(Type))
                                )
                            )
                        );

                    foreach (var methodInfo in infertaceType.GetMethods())
                    {
                        CodeMemberMethod clientMethod = new CodeMemberMethod();
                        clientDeclaration.Members.Add(clientMethod);
                        clientMethod.Attributes = MemberAttributes.Public;
                        clientMethod.Name = methodInfo.Name;
                        clientMethod.ImplementationTypes.Add(infertaceType);
                        clientMethod.ReturnType = new CodeTypeReference(methodInfo.ReturnType);
                        foreach (var parameterInfo in methodInfo.GetParameters())
                        {
                            clientMethod.Parameters.Add(new CodeParameterDeclarationExpression(parameterInfo.ParameterType, parameterInfo.Name));
                        }

                        CodeExpression execution = new CodeMethodInvokeExpression(
                            new CodeThisReferenceExpression(),
                            "Execute",
                            new CodeExpression[] { 
                            new CodePrimitiveExpression(methodInfo.Name) ,
                            new CodeTypeOfExpression(methodInfo.ReturnType),
                            new CodeArrayCreateExpression(
                                typeof(string),
                                methodInfo
                                    .GetParameters()
                                    .Select(p => new CodePrimitiveExpression(p.Name))
                                    .ToArray()
                                ),
                            new CodeArrayCreateExpression(
                                typeof(object),
                                methodInfo
                                    .GetParameters()
                                    .Select(p => new CodeArgumentReferenceExpression(p.Name))
                                    .ToArray()
                                ),
                        }
                            .ToArray()
                        );

                        if (methodInfo.ReturnType == typeof(void))
                        {
                            clientMethod.Statements.Add(
                                new CodeExpressionStatement(
                                    execution
                                    )
                                );
                        }
                        else
                        {
                            clientMethod.Statements.Add(
                                new CodeMethodReturnStatement(
                                    new CodeCastExpression(
                                        methodInfo.ReturnType,
                                        execution
                                        )
                                    )
                                );
                        }
                    }
                }

                CompilerParameters options = new CompilerParameters();
                options.GenerateExecutable = false;
                options.GenerateInMemory = true;
                options.IncludeDebugInformation = false;
                options.ReferencedAssemblies.AddRange(
                    new string[] { typeof(StrongTypedNodeEndpointClient).Assembly.Location, infertaceType.Assembly.Location }
                    .Concat(typeof(StrongTypedNodeEndpointClient).Assembly.GetReferencedAssemblies().Select(n => n.CodeBase))
                    .Concat(infertaceType.Assembly.GetReferencedAssemblies().Select(n => n.CodeBase))
                    .Distinct()
                    .ToArray()
                );

                CompilerResults result = codedomProvider.CompileAssemblyFromDom(options, codeCompileUnit);
                codedomProvider.Dispose();
                clientType = result.CompiledAssembly.GetType(namespaceName + "." + typeName);
                clientImplementations.Add(infertaceType, clientType);
            }
            return clientType;
        }

        public static T Create<T>(INodeEndpointClientProvider provider)
            where T : INodeEndpointClient
        {
            Type clientType = CreateClientImplementation(typeof(T));
            return (T)clientType
                .GetConstructor(new Type[] { typeof(INodeEndpointClientProvider) })
                .Invoke(new object[] { provider });
        }
    }
}
