#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\GuiApplication.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\GuiBasicControls.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\GuiListControls.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\GuiTextControls.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\GuiWindowControls.cpp"
//---------------------------------------------------------------
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\ExtendedControls\GuiComboControls.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\ExtendedControls\GuiContainerControls.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\ExtendedControls\GuiListViewControls.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\ExtendedControls\GuiMenuControls.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\ExtendedControls\GuiTextListControls.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\ExtendedControls\GuiTreeViewControls.cpp"
//---------------------------------------------------------------
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\Styles\GuiCommonStyles.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\Controls\Styles\GuiWin7Styles.cpp"
//---------------------------------------------------------------
#include "..\..\..\..\..\Candidate\GUI\GUI\GraphicsElement\GuiGraphicsComposition.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\GraphicsElement\GuiGraphicsElement.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\GraphicsElement\GuiGraphicsEventReceiver.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\GraphicsElement\GuiGraphicsHost.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\GraphicsElement\GuiGraphicsTextElement.cpp"
//---------------------------------------------------------------
#include "..\..\..\..\..\Candidate\GUI\GUI\Reflection\GuiTypeDescriptor.cpp"
//---------------------------------------------------------------
#include "..\..\..\..\..\Candidate\GUI\GUI\NativeWindow\GuiNativeWindow.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\NativeWindow\Windows\WinNativeWindow.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\NativeWindow\Windows\Direct2D\WinDirect2DApplication.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\NativeWindow\Windows\GDI\WinGDIApplication.cpp"
#include "..\..\..\..\..\Candidate\GUI\GUI\NativeWindow\Windows\GDI\WinGDI.cpp"
//---------------------------------------------------------------
#include "..\..\..\..\..\Library\Basic.cpp"
#include "..\..\..\..\..\Library\Exception.cpp"
#include "..\..\..\..\..\Library\String.cpp"
#include "..\..\..\..\..\Library\Threading.cpp"
#include "..\..\..\..\..\Library\Collections\Operation.cpp"
//#include "..\..\..\..\..\Library\Stream\Accessor.cpp"
//#include "..\..\..\..\..\Library\Stream\BroadcastStream.cpp"
//#include "..\..\..\..\..\Library\Stream\CacheStream.cpp"
//#include "..\..\..\..\..\Library\Stream\CharFormat.cpp"
#include "..\..\..\..\..\Library\Stream\FileStream.cpp"
//#include "..\..\..\..\..\Library\Stream\MemoryStream.cpp"
//#include "..\..\..\..\..\Library\Stream\MemoryWrapperStream.cpp"
//#include "..\..\..\..\..\Library\Stream\RecorderStream.cpp"
//#include "..\..\..\..\..\Library\Entity\TreeJson.cpp"
//#include "..\..\..\..\..\Library\Entity\TreeQuery.cpp"
//#include "..\..\..\..\..\Library\Entity\TreeXml.cpp"