using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Xml.Linq;
using System.Text.RegularExpressions;

namespace Codegen
{
    class Program
    {
        static string[] GetCppFiles(string projectFile)
        {
            string np = @"http://schemas.microsoft.com/developer/msbuild/2003";
            XDocument document = XDocument.Load(projectFile);
            return document
                .Root
                .Elements(XName.Get("ItemGroup", np))
                .SelectMany(e => e.Elements(XName.Get("ClCompile", np)))
                .Select(e => e.Attribute("Include").Value)
                .ToArray();
        }

        static Dictionary<string, string[]> CategorizeCodeFiles(XDocument config, string[] files)
        {
            Dictionary<string, string[]> categorizedFiles = new Dictionary<string, string[]>();
            foreach (var e in config.Root.Element("categories").Elements("category"))
            {
                string name = e.Attribute("name").Value;
                string pattern = e.Attribute("pattern").Value.ToUpper();
                string[] exceptions = e.Elements("except").Select(x => x.Attribute("filename").Value.ToUpper()).ToArray();
                categorizedFiles.Add(
                    name,
                    files
                        .Where(f => f.ToUpper().Contains(pattern))
                        .Where(f => !exceptions.Contains(Path.GetFileName(f).ToUpper()))
                        .ToArray()
                        );
            }
            return categorizedFiles;
        }

        static Dictionary<string, string[]> ScannedFiles = new Dictionary<string, string[]>();
        static Regex IncludeRegex = new Regex(@"^\s*\#include\s*""(?<path>[^""]+)""\s*$");
        static Regex IncludeSystemRegex = new Regex(@"^\s*\#include\s*\<(?<path>[^""]+)\>\s*$");

        static string[] GetIncludedFiles(string codeFile)
        {
            codeFile = Path.GetFullPath(codeFile).ToUpper();
            string[] result = null;
            if (!ScannedFiles.TryGetValue(codeFile, out result))
            {
                List<string> directIncludeFiles = new List<string>();
                foreach (var line in File.ReadAllLines(codeFile))
                {
                    Match match = IncludeRegex.Match(line);
                    if (match.Success)
                    {
                        string path = match.Groups["path"].Value;
                        path = Path.GetFullPath(Path.GetDirectoryName(codeFile) + @"\" + path).ToUpper();
                        if (!directIncludeFiles.Contains(path))
                        {
                            directIncludeFiles.Add(path);
                        }
                    }
                }

                for (int i = directIncludeFiles.Count - 1; i >= 0; i--)
                {
                    directIncludeFiles.InsertRange(i, GetIncludedFiles(directIncludeFiles[i]));
                }
                result = directIncludeFiles.Distinct().ToArray();
                ScannedFiles.Add(codeFile, result);
            }
            return result;
        }

        static void Combine(string[] files, string outputFilename, HashSet<string> systemIncludes, params string[] externalIncludes)
        {
            try
            {
                using (StreamWriter writer = new StreamWriter(new FileStream(outputFilename, FileMode.Create), Encoding.Default))
                {
                    writer.WriteLine("/***********************************************************************");
                    writer.WriteLine("THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY");
                    writer.WriteLine("DEVELOPER: 陈梓瀚(vczh)");
                    writer.WriteLine("***********************************************************************/");
                    foreach (var inc in externalIncludes)
                    {
                        writer.WriteLine("#include \"{0}\"", inc);
                    }

                    foreach (var file in files)
                    {
                        writer.WriteLine("");
                        writer.WriteLine("/***********************************************************************");
                        writer.WriteLine(file);
                        writer.WriteLine("***********************************************************************/");
                        foreach (var line in File.ReadAllLines(file, Encoding.Default))
                        {
                            Match match = null;

                            match = IncludeSystemRegex.Match(line);
                            if (match.Success)
                            {
                                if (systemIncludes.Add(match.Groups["path"].Value.ToUpper()))
                                {
                                    writer.WriteLine(line);
                                }
                            }
                            else
                            {
                                match = IncludeRegex.Match(line);
                                if (!match.Success)
                                {
                                    writer.WriteLine(line);
                                }
                            }
                        }
                    }
                }
                Console.WriteLine("Succeeded to write: {0}", outputFilename);
            }
            catch (Exception)
            {
                Console.WriteLine("Failed to write: {0}", outputFilename);
            }
        }

        static void Main(string[] args)
        {
            XDocument config = XDocument.Load("CodegenConfig.xml");
            string folder = Path.GetDirectoryName(typeof(Program).Assembly.Location) + "\\";

            string[] projectFiles = config.Root
                .Element("projects")
                .Elements("project")
                .Select(e => Path.GetFullPath(folder + e.Attribute("path").Value))
                .ToArray();

            string[] unprocessedCppFiles = projectFiles.SelectMany(GetCppFiles).ToArray();
            string[] unprocessedHeaderFiles = unprocessedCppFiles.SelectMany(GetIncludedFiles).ToArray();

            var categorizedCppFiles = CategorizeCodeFiles(config, unprocessedCppFiles);
            var categorizedHeaderFiles = CategorizeCodeFiles(config, unprocessedHeaderFiles);
            var outputFolder = Path.GetFullPath(folder + config.Root.Element("output").Attribute("path").Value);
            var categorizedOutput = config.Root
                .Element("output")
                .Elements("codepair")
                .ToDictionary(e => e.Attribute("category").Value, e => Path.GetFullPath(outputFolder + e.Attribute("filename").Value));
        }
    }
}
