//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoShell.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除当前显示的消息.
        /// </summary>
        internal static string CommandDescription_Clear {
            get {
                return ResourceManager.GetString("CommandDescription_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出程序.
        /// </summary>
        internal static string CommandDescription_File_Exit {
            get {
                return ResourceManager.GetString("CommandDescription_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打印出所有命令及其描述.
        /// </summary>
        internal static string CommandDescription_Help {
            get {
                return ResourceManager.GetString("CommandDescription_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开选项窗口.
        /// </summary>
        internal static string CommandDescription_Tools_Options {
            get {
                return ResourceManager.GetString("CommandDescription_Tools_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开命令行窗口.
        /// </summary>
        internal static string CommandDescription_View_CommandWindow {
            get {
                return ResourceManager.GetString("CommandDescription_View_CommandWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开输出窗口.
        /// </summary>
        internal static string CommandDescription_View_OutputWindow {
            get {
                return ResourceManager.GetString("CommandDescription_View_OutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能在初始化完成之后添加UI项。.
        /// </summary>
        internal static string ExceptionAddGroupAfterInitialization {
            get {
                return ResourceManager.GetString("ExceptionAddGroupAfterInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令&quot;{0}&quot;没有被注册。.
        /// </summary>
        internal static string ExceptionCommandNotExists {
            get {
                return ResourceManager.GetString("ExceptionCommandNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedCommand {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShellGroup&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedGroup {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedOption {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项编辑器&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedOptionEditor {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedOptionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出频道&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedOutputChannel {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedOutputChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务类型&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedService {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具窗口&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedToolWindiw {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedToolWindiw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令名不可为空。.
        /// </summary>
        internal static string ExceptionNullCommandName {
            get {
                return ResourceManager.GetString("ExceptionNullCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具窗口的工具栏不能被取消。.
        /// </summary>
        internal static string ExceptionNullToolWindowToolBarGroup {
            get {
                return ResourceManager.GetString("ExceptionNullToolWindowToolBarGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项编辑器&quot;{0}&quot;没有被注册。.
        /// </summary>
        internal static string ExceptionOptionEditorNoExists {
            get {
                return ResourceManager.GetString("ExceptionOptionEditorNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项&quot;{0}&quot;没有被注册。.
        /// </summary>
        internal static string ExceptionOptionNotExists {
            get {
                return ResourceManager.GetString("ExceptionOptionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出频道&quot;{0}&quot;没有被注册。.
        /// </summary>
        internal static string ExceptionOutputChannelNotExists {
            get {
                return ResourceManager.GetString("ExceptionOutputChannelNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具窗口的工具栏只能设置一次。.
        /// </summary>
        internal static string ExceptionResetToolWindowToolBarGroup {
            get {
                return ResourceManager.GetString("ExceptionResetToolWindowToolBarGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具窗口&quot;{0}&quot;没有被注册。.
        /// </summary>
        internal static string ExceptionToolWindowNotExists {
            get {
                return ResourceManager.GetString("ExceptionToolWindowNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令{0}执行成功。.
        /// </summary>
        internal static string LogCommandExecuted {
            get {
                return ResourceManager.GetString("LogCommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插件{0}加载成功。.
        /// </summary>
        internal static string LogPackageLoaded {
            get {
                return ResourceManager.GetString("LogPackageLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务{0}注册成功。.
        /// </summary>
        internal static string LogServiceCreated {
            get {
                return ResourceManager.GetString("LogServiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停靠在底部(&amp;B).
        /// </summary>
        internal static string MenuTextDockBottom {
            get {
                return ResourceManager.GetString("MenuTextDockBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭{0}(&amp;X).
        /// </summary>
        internal static string MenuTextDockClose {
            get {
                return ResourceManager.GetString("MenuTextDockClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭其他窗口(&amp;A).
        /// </summary>
        internal static string MenuTextDockCloseAllButThis {
            get {
                return ResourceManager.GetString("MenuTextDockCloseAllButThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停靠在文档区(&amp;D).
        /// </summary>
        internal static string MenuTextDockDocument {
            get {
                return ResourceManager.GetString("MenuTextDockDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 浮动(&amp;F).
        /// </summary>
        internal static string MenuTextDockFloating {
            get {
                return ResourceManager.GetString("MenuTextDockFloating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭{0}(&amp;X).
        /// </summary>
        internal static string MenuTextDockHide {
            get {
                return ResourceManager.GetString("MenuTextDockHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停靠在左边(&amp;L).
        /// </summary>
        internal static string MenuTextDockLeft {
            get {
                return ResourceManager.GetString("MenuTextDockLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停靠在右边(&amp;R).
        /// </summary>
        internal static string MenuTextDockRight {
            get {
                return ResourceManager.GetString("MenuTextDockRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停靠在顶部(&amp;T).
        /// </summary>
        internal static string MenuTextDockTop {
            get {
                return ResourceManager.GetString("MenuTextDockTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件(&amp;F).
        /// </summary>
        internal static string MenuTextFile {
            get {
                return ResourceManager.GetString("MenuTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出(&amp;X).
        /// </summary>
        internal static string MenuTextFileExit {
            get {
                return ResourceManager.GetString("MenuTextFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助(&amp;H).
        /// </summary>
        internal static string MenuTextHelp {
            get {
                return ResourceManager.GetString("MenuTextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于{0}(&amp;A)....
        /// </summary>
        internal static string MenuTextHelpAbout {
            get {
                return ResourceManager.GetString("MenuTextHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具(&amp;T).
        /// </summary>
        internal static string MenuTextTools {
            get {
                return ResourceManager.GetString("MenuTextTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项(&amp;O)....
        /// </summary>
        internal static string MenuTextToolsOptions {
            get {
                return ResourceManager.GetString("MenuTextToolsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 视图(&amp;V).
        /// </summary>
        internal static string MenuTextView {
            get {
                return ResourceManager.GetString("MenuTextView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令行窗口(&amp;C).
        /// </summary>
        internal static string MenuTextViewCommandWindow {
            get {
                return ResourceManager.GetString("MenuTextViewCommandWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出窗口(&amp;O).
        /// </summary>
        internal static string MenuTextViewOutputWindow {
            get {
                return ResourceManager.GetString("MenuTextViewOutputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工具栏(&amp;T).
        /// </summary>
        internal static string MenuTextViewToolbars {
            get {
                return ResourceManager.GetString("MenuTextViewToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 窗口(&amp;W).
        /// </summary>
        internal static string MenuTextWindow {
            get {
                return ResourceManager.GetString("MenuTextWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 环境设置.
        /// </summary>
        internal static string OptionNameEnvironment {
            get {
                return ResourceManager.GetString("OptionNameEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoShell记录.
        /// </summary>
        internal static string OutputChannelAutoShell {
            get {
                return ResourceManager.GetString("OutputChannelAutoShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        internal static string ToolItemClearChannel {
            get {
                return ResourceManager.GetString("ToolItemClearChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出频道：.
        /// </summary>
        internal static string ToolItemOutput {
            get {
                return ResourceManager.GetString("ToolItemOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空当前输出频道的消息.
        /// </summary>
        internal static string ToolTipClearChannel {
            get {
                return ResourceManager.GetString("ToolTipClearChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命令行.
        /// </summary>
        internal static string ToolWindowCommand {
            get {
                return ResourceManager.GetString("ToolWindowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出.
        /// </summary>
        internal static string ToolWindowOutput {
            get {
                return ResourceManager.GetString("ToolWindowOutput", resourceCulture);
            }
        }
    }
}
