//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoShell.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制当前文档选中的部分.
        /// </summary>
        internal static string CommandDescription_Edit_Copy {
            get {
                return ResourceManager.GetString("CommandDescription_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切当前文档选中的部分.
        /// </summary>
        internal static string CommandDescription_Edit_Cut {
            get {
                return ResourceManager.GetString("CommandDescription_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除当前文档选中的部分.
        /// </summary>
        internal static string CommandDescription_Edit_Delete {
            get {
                return ResourceManager.GetString("CommandDescription_Edit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把剪贴板的内容粘帖到当前文档.
        /// </summary>
        internal static string CommandDescription_Edit_Paste {
            get {
                return ResourceManager.GetString("CommandDescription_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做最近的一次修改.
        /// </summary>
        internal static string CommandDescription_Edit_Redo {
            get {
                return ResourceManager.GetString("CommandDescription_Edit_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选中当前文档的所有内容.
        /// </summary>
        internal static string CommandDescription_Edit_SelectAll {
            get {
                return ResourceManager.GetString("CommandDescription_Edit_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销最近的一次修改.
        /// </summary>
        internal static string CommandDescription_Edit_Undo {
            get {
                return ResourceManager.GetString("CommandDescription_Edit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭当前文档.
        /// </summary>
        internal static string CommandDescription_File_Close {
            get {
                return ResourceManager.GetString("CommandDescription_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建文件.
        /// </summary>
        internal static string CommandDescription_File_New_File {
            get {
                return ResourceManager.GetString("CommandDescription_File_New_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件.
        /// </summary>
        internal static string CommandDescription_File_Open_File {
            get {
                return ResourceManager.GetString("CommandDescription_File_Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存当前文档.
        /// </summary>
        internal static string CommandDescription_File_Save {
            get {
                return ResourceManager.GetString("CommandDescription_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存所有打开的文档.
        /// </summary>
        internal static string CommandDescription_File_SaveAll {
            get {
                return ResourceManager.GetString("CommandDescription_File_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将当前文档另存为.
        /// </summary>
        internal static string CommandDescription_File_SaveAs {
            get {
                return ResourceManager.GetString("CommandDescription_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件.
        /// </summary>
        internal static string DialogOpen {
            get {
                return ResourceManager.GetString("DialogOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存文件.
        /// </summary>
        internal static string DialogSave {
            get {
                return ResourceManager.GetString("DialogSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件组&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedFileCategory {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedFileCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件编辑器&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedFileEditor {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedFileEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件类型&quot;{0}&quot;已经被注册。.
        /// </summary>
        internal static string ExceptionDuplicatedFileType {
            get {
                return ResourceManager.GetString("ExceptionDuplicatedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定的编辑器工具窗口&quot;{0}&quot;没有继承自IEditorWindow。.
        /// </summary>
        internal static string ExceptionEditorWindowDoesNotImplementIEditorWindow {
            get {
                return ResourceManager.GetString("ExceptionEditorWindowDoesNotImplementIEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件组&quot;{0}&quot;没有被注册。.
        /// </summary>
        internal static string ExceptionFileCategoryNotExists {
            get {
                return ResourceManager.GetString("ExceptionFileCategoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件编辑器&quot;{0}&quot;没有被注册。.
        /// </summary>
        internal static string ExceptionFileEditorNotExists {
            get {
                return ResourceManager.GetString("ExceptionFileEditorNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件类型&quot;{0}&quot;没有被注册。.
        /// </summary>
        internal static string ExceptionFileTypeNotExists {
            get {
                return ResourceManager.GetString("ExceptionFileTypeNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1})|{1}.
        /// </summary>
        internal static string FileDialogFilter {
            get {
                return ResourceManager.GetString("FileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑(&amp;E).
        /// </summary>
        internal static string MenuTextEdit {
            get {
                return ResourceManager.GetString("MenuTextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制(&amp;C).
        /// </summary>
        internal static string MenuTextEditCopy {
            get {
                return ResourceManager.GetString("MenuTextEditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切(&amp;T).
        /// </summary>
        internal static string MenuTextEditCut {
            get {
                return ResourceManager.GetString("MenuTextEditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除(&amp;D).
        /// </summary>
        internal static string MenuTextEditDelete {
            get {
                return ResourceManager.GetString("MenuTextEditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘帖(&amp;P).
        /// </summary>
        internal static string MenuTextEditPaste {
            get {
                return ResourceManager.GetString("MenuTextEditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做(&amp;R).
        /// </summary>
        internal static string MenuTextEditRedo {
            get {
                return ResourceManager.GetString("MenuTextEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全选(&amp;A).
        /// </summary>
        internal static string MenuTextEditSelectAll {
            get {
                return ResourceManager.GetString("MenuTextEditSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销(&amp;U).
        /// </summary>
        internal static string MenuTextEditUndo {
            get {
                return ResourceManager.GetString("MenuTextEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭{0}(&amp;C).
        /// </summary>
        internal static string MenuTextFileClose {
            get {
                return ResourceManager.GetString("MenuTextFileClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建(&amp;N).
        /// </summary>
        internal static string MenuTextFileNew {
            get {
                return ResourceManager.GetString("MenuTextFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件(&amp;F)....
        /// </summary>
        internal static string MenuTextFileNewFile {
            get {
                return ResourceManager.GetString("MenuTextFileNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开(&amp;O).
        /// </summary>
        internal static string MenuTextFileOpen {
            get {
                return ResourceManager.GetString("MenuTextFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件(&amp;F)....
        /// </summary>
        internal static string MenuTextFileOpenFile {
            get {
                return ResourceManager.GetString("MenuTextFileOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最近打开的文件(&amp;F).
        /// </summary>
        internal static string MenuTextFileRecentFiles {
            get {
                return ResourceManager.GetString("MenuTextFileRecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （空）.
        /// </summary>
        internal static string MenuTextFileRecentFilesEmpty {
            get {
                return ResourceManager.GetString("MenuTextFileRecentFilesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存{0}(&amp;S)....
        /// </summary>
        internal static string MenuTextFileSave {
            get {
                return ResourceManager.GetString("MenuTextFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存所有文件(&amp;L).
        /// </summary>
        internal static string MenuTextFileSaveAll {
            get {
                return ResourceManager.GetString("MenuTextFileSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 另存为(&amp;A)....
        /// </summary>
        internal static string MenuTextFileSaveAs {
            get {
                return ResourceManager.GetString("MenuTextFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有窗口(&amp;A)....
        /// </summary>
        internal static string MenuTextWindowWindows {
            get {
                return ResourceManager.GetString("MenuTextWindowWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有安装可以编辑文件{0}的编辑器。.
        /// </summary>
        internal static string MessageBoxNoAssociatedEditor {
            get {
                return ResourceManager.GetString("MessageBoxNoAssociatedEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否保存对{0}的更改？.
        /// </summary>
        internal static string MessageBoxSaveModificationTo {
            get {
                return ResourceManager.GetString("MessageBoxSaveModificationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准.
        /// </summary>
        internal static string ToolBarStandard {
            get {
                return ResourceManager.GetString("ToolBarStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string ToolTipStandardCopy {
            get {
                return ResourceManager.GetString("ToolTipStandardCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剪切.
        /// </summary>
        internal static string ToolTipStandardCut {
            get {
                return ResourceManager.GetString("ToolTipStandardCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建文件.
        /// </summary>
        internal static string ToolTipStandardNew {
            get {
                return ResourceManager.GetString("ToolTipStandardNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开文件.
        /// </summary>
        internal static string ToolTipStandardOpen {
            get {
                return ResourceManager.GetString("ToolTipStandardOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 粘贴.
        /// </summary>
        internal static string ToolTipStandardPaste {
            get {
                return ResourceManager.GetString("ToolTipStandardPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重做.
        /// </summary>
        internal static string ToolTipStandardRedo {
            get {
                return ResourceManager.GetString("ToolTipStandardRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存{0}.
        /// </summary>
        internal static string ToolTipStandardSave {
            get {
                return ResourceManager.GetString("ToolTipStandardSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存所有文件.
        /// </summary>
        internal static string ToolTipStandardSaveAll {
            get {
                return ResourceManager.GetString("ToolTipStandardSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撤销.
        /// </summary>
        internal static string ToolTipStandardUndo {
            get {
                return ResourceManager.GetString("ToolTipStandardUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未命名&lt;{0}&gt;*.
        /// </summary>
        internal static string ToolWindowUnsavedDocument {
            get {
                return ResourceManager.GetString("ToolWindowUnsavedDocument", resourceCulture);
            }
        }
    }
}
