/***********************************************************************
DO NOT MODIFY!!!
THIS FILE IS AUTO GENERATED BY _TranslateXMLtoCode.exe

Developer: 陈梓瀚(vczh)
***********************************************************************/

#include "GuiTypeDescriptorImpProvider_codegen.h"

namespace vl
{
	namespace presentation
	{
		namespace reflection_implementation
		{

/***********************************************************************
Helper Functions
***********************************************************************/

			ITypeProvider* CreateDefaultTypeProvider()
			{
				return 0;
			}
		}
	}
}
