/***********************************************************************
DO NOT MODIFY!!!
THIS FILE IS AUTO GENERATED BY _TranslateXMLtoCode.exe

Developer: 陈梓瀚(vczh)
***********************************************************************/

#include "GuiTypeDescriptorImpHelper.h"

namespace vl
{
	namespace presentation
	{
		namespace reflection_implementation
		{
			extern ITypeProvider* CreateDefaultTypeProvider();
		}
	}
}
