//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoShell.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在当前选择的范围内找不到&quot;{0}&quot;。.
        /// </summary>
        internal static string FindNotValue {
            get {
                return ResourceManager.GetString("FindNotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有打开的文档.
        /// </summary>
        internal static string FindTargetGroupAllOpenDocuments {
            get {
                return ResourceManager.GetString("FindTargetGroupAllOpenDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前打开的文档.
        /// </summary>
        internal static string FindTargetGroupCurrentWindow {
            get {
                return ResourceManager.GetString("FindTargetGroupCurrentWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行号（1 - {0}）：.
        /// </summary>
        internal static string GotoFormLabelText {
            get {
                return ResourceManager.GetString("GotoFormLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找(&amp;F).
        /// </summary>
        internal static string MenuTextEditFind {
            get {
                return ResourceManager.GetString("MenuTextEditFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在文件中查找(&amp;I)....
        /// </summary>
        internal static string MenuTextEditFindFindInFiles {
            get {
                return ResourceManager.GetString("MenuTextEditFindFindInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速查找(&amp;F)....
        /// </summary>
        internal static string MenuTextEditFindQuickFind {
            get {
                return ResourceManager.GetString("MenuTextEditFindQuickFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速替换(&amp;R)....
        /// </summary>
        internal static string MenuTextEditFindQuickReplace {
            get {
                return ResourceManager.GetString("MenuTextEditFindQuickReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在文件中替换(&amp;S)....
        /// </summary>
        internal static string MenuTextEditFindReplaceInFiles {
            get {
                return ResourceManager.GetString("MenuTextEditFindReplaceInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跳转(&amp;G)....
        /// </summary>
        internal static string MenuTextEditGoTo {
            get {
                return ResourceManager.GetString("MenuTextEditGoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找结果窗口(&amp;F).
        /// </summary>
        internal static string MenuTextViewFindResultWindow {
            get {
                return ResourceManager.GetString("MenuTextViewFindResultWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找选项.
        /// </summary>
        internal static string OptionNameFind {
            get {
                return ResourceManager.GetString("OptionNameFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在文件中查找.
        /// </summary>
        internal static string ToolItemFindInFiles {
            get {
                return ResourceManager.GetString("ToolItemFindInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速查找.
        /// </summary>
        internal static string ToolItemQuickFind {
            get {
                return ResourceManager.GetString("ToolItemQuickFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速替换.
        /// </summary>
        internal static string ToolItemQuickReplace {
            get {
                return ResourceManager.GetString("ToolItemQuickReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在文件中替换.
        /// </summary>
        internal static string ToolItemReplaceInFiles {
            get {
                return ResourceManager.GetString("ToolItemReplaceInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除查找结果.
        /// </summary>
        internal static string ToolTipClearFindResult {
            get {
                return ResourceManager.GetString("ToolTipClearFindResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开后一个查找结果.
        /// </summary>
        internal static string ToolTipNextFindResult {
            get {
                return ResourceManager.GetString("ToolTipNextFindResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开当前查找结果.
        /// </summary>
        internal static string ToolTipOpenFindResult {
            get {
                return ResourceManager.GetString("ToolTipOpenFindResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开前一个查找结果.
        /// </summary>
        internal static string ToolTipPreviousFindResult {
            get {
                return ResourceManager.GetString("ToolTipPreviousFindResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止查找.
        /// </summary>
        internal static string ToolTipStopBackgroundFind {
            get {
                return ResourceManager.GetString("ToolTipStopBackgroundFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找与替换 -- {0}.
        /// </summary>
        internal static string ToolWindowFind {
            get {
                return ResourceManager.GetString("ToolWindowFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找结果（{0}）.
        /// </summary>
        internal static string ToolWindowFindResult {
            get {
                return ResourceManager.GetString("ToolWindowFindResult", resourceCulture);
            }
        }
    }
}
