Vle.exe make "..\..\..\..\UnitTest\Binary\ScriptCoreLibrary\System.CoreNative.Make.txt"
Vle.exe make "..\..\..\..\UnitTest\Binary\ScriptCoreLibrary\System.UnitTestNative.Make.txt"
Vle.exe make "..\..\..\..\UnitTest\Binary\ScriptCoreLibrary\System.ConsoleNative.Make.txt"

copy Vle.exe "..\..\vlpp\Vle.exe"
copy VlScript.dll "..\..\vlpp\VlScript.dll"
copy VlScript.lib "..\..\vlpp\VlScript.lib"
copy VlScript.lib "..\..\vlpp\VlScript.lib"
copy "..\VlScript\VlScript.h" "..\..\vlpp\VlScript.h"
copy VlScriptDotNet.dll "..\..\vlpp\VlScriptDotNet.dll"

copy "..\..\..\..\UnitTest\Binary\ScriptCoreLibrary\Binary\Assembly.syscrnat.assembly" "..\..\vlpp\Assembly.syscrnat.assembly"
copy "..\..\..\..\UnitTest\Binary\ScriptCoreLibrary\Binary\Assembly.sysutnat.assembly" "..\..\vlpp\Assembly.sysutnat.assembly"
copy "..\..\..\..\UnitTest\Binary\ScriptCoreLibrary\Binary\Assembly.syscsnat.assembly" "..\..\vlpp\Assembly.syscsnat.assembly"
Vle.exe header NativeX "..\..\vlpp\Assembly.syscrnat.assembly" "..\..\vlpp\Header.syscrnat.NativeX.txt"
Vle.exe header NativeX "..\..\vlpp\Assembly.sysutnat.assembly" "..\..\vlpp\Header.sysutnat.NativeX.txt"
Vle.exe header NativeX "..\..\vlpp\Assembly.syscsnat.assembly" "..\..\vlpp\Header.syscsnat.NativeX.txt"

copy Developer.LanguageProvider.dll "..\..\vlpp\Turtle\Developer.LanguageProvider.dll"
copy Developer.LanguageServices.NativeX.dll "..\..\vlpp\Turtle\Developer.LanguageServices.NativeX.dll"
copy Developer.WinFormControls.dll "..\..\vlpp\Turtle\Developer.WinFormControls.dll"
copy Developer.RibbonFramework.dll "..\..\vlpp\Turtle\Developer.RibbonFramework.dll"
copy Developer.RibbonFramework.dll "..\..\vlpp\Turtle\Developer.RibbonFramework.dll"
copy VlScriptDotNet.dll "..\..\vlpp\Turtle\VlScriptDotNet.dll"
copy VlTurtle.exe "..\..\vlpp\Turtle\VlTurtle.exe"
copy Vle.exe "..\..\vlpp\Turtle\Vle.exe"
copy VlScript.dll "..\..\vlpp\Turtle\VlScript.dll"
copy "Script\Turtle.Make.txt" "..\..\vlpp\Turtle\Script\Turtle.Make.txt"
copy "Script\Turtle.NativeX.txt" "..\..\vlpp\Turtle\Script\Turtle.NativeX.txt"
copy "Script\NativeX\Make.txt" "..\..\vlpp\Turtle\Script\NativeX\Make.txt"

Vle.exe make "Script\Turtle.Make.txt"
Vle.exe make "..\..\vlpp\Turtle\Script\Turtle.Make.txt"

copy "..\..\vlpp\Assembly.syscrnat.assembly" "..\..\vlpp\Turtle\Assembly.syscrnat.assembly"
copy "..\..\vlpp\Header.syscrnat.NativeX.txt" "..\..\vlpp\Turtle\Header.syscrnat.NativeX.txt"

copy "..\..\vlpp\Assembly.syscrnat.assembly" "Assembly.syscrnat.assembly"
copy "..\..\vlpp\Header.syscrnat.NativeX.txt" "Header.syscrnat.NativeX.txt"